disabled_rules:
  - colon
  - comma
  - control_statement
opt_in_rules:
  - empty_count

included:
  - Noble-iOS
excluded:
  - Noble-iOSTests
  - Noble-iOSUITests

identifier_name:
  excluded:
    - id
reporter: "xcode"
